# Generated by Django 5.0.2 on 2024-03-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apimodel',
            old_name='botao',
            new_name='Botao',
        ),
        migrations.RenameField(
            model_name='apimodel',
            old_name='liga_robo',
            new_name='LigaRobo',
        ),
        migrations.RenameField(
            model_name='apimodel',
            old_name='reset_contador',
            new_name='ResetContador',
        ),
        migrations.RenameField(
            model_name='apimodel',
            old_name='sensor',
            new_name='Sensor',
        ),
        migrations.RenameField(
            model_name='apimodel',
            old_name='valor_contagem',
            new_name='Valor_Contagem',
        ),
    ]
